### ISSUE TITLE
still seeing some odd columns behavior. 

### ISSUE THREAD

**Issue by bgilmore-splunk** [IOT-DSA/dslink-java-splunk#2]
<img width="1335" alt="screen shot 2015-07-31 at 6 33 03 pm" src="https://cloud.githubusercontent.com/assets/7364065/9020180/a1854afe-37b2-11e5-8a2e-d42d34c28aa3.png">

duplicate columns, appears yesterdays issue is resolved and this is new, but hard to fully test.

**Comment by samrg472** [comment]
Is this still an issue?

**Comment by bgilmore-splunk** [comment]
Nope that was fixed. Thanks!

Sent from my iPhone

On Aug 6, 2015, at 5:12 PM, samrg472 <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this still an issue?
